import pyautogui as p, time
p.PAUSE = 1
time.sleep(5)
p.typewrite("The world around us is changing fast,")
p.typewrite(["enter"])
p.typewrite("A warming trend that seems to last.")
p.typewrite(["enter"])
p.typewrite("The seasons blend and the winds grow strong,")
p.typewrite(["enter"])
p.typewrite("The weather patterns all seem wrong.")
p.typewrite(["enter"])
p.typewrite(["enter"])
p.typewrite("The ice caps shrink, the sea levels rise,")
p.typewrite(["enter"])
p.typewrite("Wildfires rage beneath the skies.")
p.typewrite(["enter"])
p.typewrite("The storms grow fierce, the droughts extend,")
p.typewrite(["enter"])
p.typewrite("The consequences, we cannot pretend.")
p.typewrite(["enter"])
p.typewrite(["enter"])
p.typewrite("The air we breathe is thick with smog,")
p.typewrite(["enter"])
p.typewrite("The forests fall, the coral clog.")
p.typewrite(["enter"])
p.typewrite("The oceans heat, the wildlife dies,")
p.typewrite(["enter"])
p.typewrite("The future dims before our eyes.")
p.typewrite(["enter"])
p.typewrite(["enter"])
p.typewrite("But hope remains, if we act now,")
p.typewrite(["enter"])
p.typewrite("We can reverse this fatal plow.")
p.typewrite(["enter"])
p.typewrite("The time is now, we must unite,")
p.typewrite(["enter"])
p.typewrite("To save our planet, it's worth the fight.")
p.typewrite(["enter"])
p.typewrite(["enter"])
p.typewrite("Reduce, reuse, recycle too,")
p.typewrite(["enter"])
p.typewrite("Plant trees, conserve, it's up to you.")
p.typewrite(["enter"])
p.typewrite("Together we can make a change,")
p.typewrite(["enter"])
p.typewrite("And protect our world from climate's range.")